name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  CI:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Build with Gradle
        run: ./gradlew clean build

  CD:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Install MySQL Client
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create application.yml
        run: |
          cat << EOF > src/main/resources/application.yml
          spring:
            datasource:
              url: jdbc:mysql://${{ secrets.DB_IP }}:${{ secrets.DB_PORT }}/${{ secrets.DB_NAME }}
              username: ${{ secrets.DB_USERNAME }}
              password: ${{ secrets.DB_PASSWORD }}
            jpa:
              hibernate:
                ddl-auto: update
              show-sql: true
          EOF
      - name: Deploy to Naver Cloud Platform
        env:
          SERVER_ADMIN_PASSWORD: ${{ secrets.SERVER_ADMIN_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "$SERVER_ADMIN_PASSWORD" scp -o StrictHostKeyChecking=no -P $SERVER_PORT ./src/main/resources/application.yml $SERVER_USER@$SERVER_IP:/opt/social-commerce-platform
          sshpass -p "$SERVER_ADMIN_PASSWORD" scp -o StrictHostKeyChecking=no -P $SERVER_PORT ${{ env.ARTIFACT_PATH }} $SERVER_USER@$SERVER_IP:/opt/social-commerce-platform
